server.port=${PORT:3001}
server.servlet.context-path=/api
spring.application.name=tripin-api-java
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.problemdetails.enabled=false
debug=false
logging.level.root=INFO
spring.sql.init.mode=never
